# Generated by Django 5.2.6 on 2025-10-19 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('episodes', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=16)),
                ('desc', models.TextField()),
                ('bg', models.ImageField(upload_to='bg/')),
                ('thumb', models.ImageField(upload_to='thumb/')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
        ),
    ]
