# Generated by Django 5.2.6 on 2025-10-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('episodes', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=16)),
                ('desc', models.TextField()),
                ('bg', models.URLField()),
                ('thumb', models.URLField()),
            ],
        ),
    ]
