# Generated by Django 5.2.6 on 2025-10-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bg',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.CharField(max_length=255),
        ),
    ]
