# Generated by Django 5.2.6 on 2025-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_bg_alter_movie_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bg',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.URLField(),
        ),
    ]
