# Generated by Django 5.2.6 on 2025-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_bg_alter_movie_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bg',
            field=models.ImageField(upload_to='bg/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(upload_to='thumb/'),
        ),
    ]
